const paquetes = [
    {
        id: 1,
        destino: "Miami",
        precio: 6500,
        img: src="../img/miami.jpg",
        cantidad: 1,
        tipo: "internacional",
    },
    {
        id: 5,
        destino: "Iguazu",
        precio: 9300,
        img: src="../img/iguazu.jpg",
        cantidad: 1,
        tipo: "nacional",
    },
    {
        id: 2,
        destino: "Londres",
        precio: 10500,
        img: src="../img/londres.jpg",
        cantidad: 1,
        tipo: "internacional",
    },
    {
        id: 6,
        destino: "Ushuaia",
        precio: 19500,
        img: src="../img/ushuaia.jpg",
        cantidad: 1,
        tipo: "nacional",
    },
    {
        id: 3,
        destino: "Paris",
        precio: 18500,
        img: src="../img/paris.jpg",
        cantidad: 1,
        tipo: "internacional",
    },
    {
        id: 7,
        destino: "Bariloche",
        precio: 28500,
        img: src="../img/bariloche.jpg",
        cantidad: 1,
        tipo: "nacional",
    },
    {
        id: 4,
        destino: "Caribe",
        precio: 6300,
        img: src="../img/punta_cana.jpg",
        cantidad: 1,
        tipo: "internacional",
    },
    {
        id: 8,
        destino: "Tour CABA",
        precio: 5300,
        img: src="../img/helicopteroBA.jpg",
        cantidad: 1,
        tipo: "nacional",
    },


];